### ISSUE TITLE
Copy updates

### ISSUE THREAD

**Issue by samuwen** [AhoyLemon/wrongest.website#3]
change "Anyone who goes to that URL will join your lobby" to "Anyone who goes to that URL can enter their name, and then will join your lobby"

change "Gameplay continues like this until we can declare a winner" to whatever the win condition is (4 rounds at the moment?)

change "The leader can adjust settings using the gear button" to "You can adjust settings using the gear button"

add in "as the person who created the game, you get to be the dealer for the first round!" <-- unless dealer will be randomly assigned on gamestart.

remove "Statements voted most wrong are tracked, so that we can pay attention to this sort of thing later." <-- this is irrelevant for users.

**Comment by samuwen** [comment]
Change "Playable on any device with a modern browser, and supports 3-8 players." to "It is playable on any device with a modern browser, and supports 3-8 players."

change "It's more fun to to keep the topic itself secret, just dance around the underpinning logic" to "It's more fun to to keep the topic itself secret, and just dance around the underpinning logic"

change "Occasionally, a statement will be marked "hard", that's worth bonus points." to "Occasionally, a statement will be marked "hard", it's worth bonus points!"

In "You'll be given a list of statements (excluding your own), and you most vote for one most wrong and one least wrong statement." there's a spelling error. 'most' should be 'must' (also in the parenthetical issue FYI)

change "I think you've got the idea by now, so how about you..." to "You've got the idea by now, so how about you..."

**Comment by AhoyLemon** [comment]
- Ignoring the "4 rounds" note, as win conditions are kind of abstract at the mo. This'll get clarified with playtesting.
- Tweaked dealer language.

> remove "Statements voted most wrong are tracked, so that we can pay attention to this sort of thing later." <-- this is irrelevant for users.
- I disagree. I think I've worded this poorly but there's an idea that we're actually tracking **The Wrongest Words**, which is relevant. Also, you have to thumbs-down something, so that action needs to feel meaningful.

> change "Occasionally, a statement will be marked "hard", that's worth bonus points." to "Occasionally, a statement will be marked "hard", it's worth bonus points!"
- I'll meet you halfway, but I'm not abusing exclamation points like that.

All other notes cheerfully accepted.
