### ISSUE TITLE
Mobile - How to Play obscures the "play now" button

### ISSUE THREAD

**Issue by samuwen** [AhoyLemon/wrongest.website#6]
Both on chrome and safari (iphone) the how to play section displays over the play now button (portrait mode). The display is slightly better in chrome, as you can see a portion of the button. It is completely obscured in safari.

**Comment by AhoyLemon** [comment]
How about now?

**Comment by samuwen** [comment]
Mostly better. Safari is cut off, and the text below both buttons is still scrolled out of view.

**Comment by AhoyLemon** [comment]
Okay, how about now?
