### ISSUE TITLE
tan text box lower border

### ISSUE THREAD

**Issue by samuwen** [AhoyLemon/wrongest.website#7]
the text blocks that describe functionality (used for tan text boxes) have a larger footer size than header size. this looks fine on desktop but kinda looks shitty on mobile.

**Comment by AhoyLemon** [comment]
I don't get what you mean.

**Comment by samuwen** [comment]
I'll SS this when I'm at work (free snagit)

**Comment by samuwen** [comment]
![space](https://cloud.githubusercontent.com/assets/7898671/6872835/1412f1aa-d469-11e4-9fcd-12e1056902a7.png)

**Comment by AhoyLemon** [comment]
Oh, got it. Thanks.

**Comment by AhoyLemon** [comment]
Closed in 548dc8f
