### ISSUE TITLE
Remove parentheticals

### ISSUE THREAD

**Issue by samuwen** [AhoyLemon/wrongest.website#8]
The parenthetical statements can be expressed with regular sentences and feels less "conversational".

change "Your job is try to convince the other players that your statement (which they cannot see) is actually true." to "Your job is to try to convince the other players that your statement is actually true. Other players are unable to see your statement while you present."

change "You'll be given a list of statements (excluding your own), and you most vote for one most wrong and one least wrong statement." to "You'll be given a list of the other player's statements, and you must vote for one most wrong and one least wrong statement."

**Comment by AhoyLemon** [comment]
1. Agreed, with slight copy tweak.
   2 Agreed, but with removing the second use of "statement".
